spring.application.name=tts

spring.datasource.url=jdbc:postgresql://localhost:5432/tts_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

elevenlabs.api.key=${ELEVENLABS_API_KEY}
elevenlabs.api.base-url=https://api.elevenlabs.io/v1


audio.storage.path=./audio-storage

app.cors.allowed-origin=http://localhost:5173


jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000


server.port=8080

